### ISSUE TITLE
CoverLetter

### ISSUE THREAD

**Issue by FranklinYinanDing** [legend80s/personal#1]
Bold important information like front-end engineer, Angela Zhu, BUPT, Master, Alibaba...

> I learnt about it...

it -> this awesome opportunity.

> WeChat blog.
- enter

> This position can ...

I believe my technical background makes me an outstanding fit for this front-end engineer position. With my knowledge and experience in Web Development, I can help Airbnb be more localized and popular in the China market.

> I got Master...BUPT

remove

> and have 1.5... Inc.

I have been working as a front-end engineer in Alibaba Inc for 2 years.

> I believe...

remove

> I am eager ...

Apart from the engineering side, as a regular traveller myself, I share the same value as Airbnb's passion, mission and vision in...

**Comment by legend80s** [comment]
**Thanks very much!**
- I don't understand this tip, what should I do with this one?
  
  > WeChat blog.
