### ISSUE TITLE
Resume

### ISSUE THREAD

**Issue by FranklinYinanDing** [legend80s/personal#2]
Add summarize after the line of Alibaba Inc.

Move OpenSearch in a bullet point.

Italic technical words, like "Augular1", "Javascript"...

> Take part in making the rules and ...

Design and implement ...

> Proactively...

Standardize the internal code style, including ...

> Take part in ...

Build the internal front-end unit test framework with ...

Master degree doesn't match cover letter.

Too much blank on the bottom.

**Comment by legend80s** [comment]
**Thanks very much**
- For _unit test_, I think it should be _unit testing_, Here is the sentence abstracted from [Wikipedia](https://en.wikipedia.org/wiki/Unit_testing)
  
  > In computer programming, unit testing is a software testing method by which individual units of source code...
